# Generated by Django 2.1.15 on 2020-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimenus', '0005_auto_20200415_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Page url, can be absolute or related.', max_length=200, null=True),
        ),
    ]
